---
title: "movie_vig"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{movie_vig}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  eval = TRUE
)
```

```{r setup}
library(final.project2)
library(tidyverse)
library(broom)
```


```{r}
data("Movie_Data")
Reduced.List <- Movie_Data %>% 
  count(director_name, na.rm = TRUE) %>% 
  filter(n >= 6) %>%
  slice(-1)

ReducedMovies <- Movie_Data %>%
  semi_join(Reduced.List, by = "director_name")
```

```{r}
#Multiple regression model that predicts gross from director name, actor name, 
#budget, duration, content rating, and year released
multiple.mod = lm(gross ~ director_name + budget + duration + actor_1_name + content_rating + imdb_score + title_year, data = ReducedMovies)
(coef(multiple.mod))
anova(multiple.mod)
max(coef(multiple.mod))
```

```{r}
#Creating a model that predicts gross based on director.
gross.mod = lm(gross ~ director_name, data = ReducedMovies)
(coef(gross.mod))
anova(gross.mod)
max(coef(gross.mod))

test <- tidy(gross.mod)
#We only want to look at directors that add at least 54,000,000 dollars to gross.
gross.data <- test %>%
  arrange(desc(estimate)) %>% 
  filter(estimate > 54000000) %>% 
  mutate(term = str_remove(term, "director_name"))
saveRDS(gross.data, file = "../data/gross.Rds")

#Plot of coefficients for directors in terms of gross added
ggplot(gross.data) + geom_col(aes(x=reorder(term, estimate), y=estimate, fill = ifelse(p.value < 0.05,'Significant','Insignificant'))) +
  labs(fill = 'p-value') +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  xlab("Director Name") + ylab("Gross Added") + ggtitle("Best Directors in Terms of Gross Added") +
  scale_y_continuous(breaks = c(0,50000000,100000000,150000000,200000000), labels = scales::comma) +
  coord_flip()
```

```{r}
#Creating a model that predicts IMDb score based on director.
imdb.mod = lm(imdb_score ~ director_name, data = ReducedMovies)
(coef(imdb.mod))
anova(imdb.mod)
max(coef(imdb.mod))

imdb.data <- tidy(imdb.mod)

#We only want to look at directors that add at least .5 IMDb points.
imdb.data <- imdb.data %>%
  arrange(desc(estimate)) %>% 
  filter(estimate > .5) %>% 
  mutate(term = str_remove(term, "director_name"))

#Plot of coefficients for directors in terms of imdb points added
ggplot(imdb.data) + geom_col(aes(x=reorder(term, estimate), y=estimate, fill = ifelse(p.value < 0.05,'Significant','Insignificant'))) +
  labs(fill = 'p-value') +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  xlab("Director Name") + ylab("IMDb Points Added") + ggtitle("Best Directors in Terms of IMDb Points Added")+
  coord_flip() 
```

```{r}
#Creating the prediction function
regression.table <- tidy(multiple.mod)%>%
  filter(term != "actor_1_nameQuentin Tarantino")%>% 
  mutate(term = str_remove(term, "director_name")) %>% 
  mutate(term = str_remove(term, "actor_1_name")) %>% 
  mutate(term = str_remove(term, "content_rating"))

```

```{r}
#Function for predicting domestic gross from several factors.
gross.predictor <- function(director_name, actor_1_name, budget = 50000000, duration = 120, content_rating = "PG-13", imdb_score = 7.5, title_year = 2019, data = regression.table) {

  budget.coef <-  as.numeric(regression.table %>% filter(term == "budget") %>% select("estimate"))
  duration.coef <-  as.numeric(regression.table %>% filter(term == "duration") %>% select("estimate"))
  director.coef <-  as.numeric(regression.table %>% filter(term == director_name) %>% select("estimate"))
  actor.coef <-  as.numeric(regression.table %>% filter(term == actor_1_name) %>% select("estimate"))
  rating.coef <-  as.numeric(regression.table %>% filter(term == content_rating) %>% select("estimate"))
  imdb.coef <-  as.numeric(regression.table %>% filter(term == "imdb_score") %>% select("estimate"))
  year.coef <-  as.numeric(regression.table %>% filter(term == "title_year") %>% select("estimate"))


  dollars <- (1938713878.08 + (director.coef) + (actor.coef) + (budget*budget.coef) + (duration*duration.coef) + (rating.coef) + (imdb_score*imdb.coef) + (title_year*year.coef))
    
  return(dollars)
}

#Examples of using the function:
gross.predictor("Christopher Nolan", "Tom Hardy", 150000000, 145, "PG-13", 8.2, 2019)
gross.predictor("Steven Spielberg", "Tom Cruise", 50000000, 130, "PG-13", 7.8, 2019)
gross.predictor("Steven Spielberg", "Tom Cruise", 50000000, 125, "PG-13", 7.8, 2019)

#Inception
gross.predictor("Christopher Nolan", "Leonardo DiCaprio", 160000000, 148, "PG-13", 8.8, 2010)

#Pulp Fiction
gross.predictor("Quentin Tarantino", "Bruce Willis", 8000000, 154, "PG-13", 8.9, 1994)

#You Don't Mess With the Zohan
gross.predictor("Dennis Dugan", "Adam Sandler", 90000000, 113, "PG-13", 5.5, 2008)

#The Usual Suspects
gross.predictor("Bryan Singer", "Kevin Spacey", 6000000, 106, "PG-13", 8.6, 1995)

#Once Upon a time in Hollywood
gross.predictor("J.J. Abrams", "Leonardo Dicaprio", 95000000, 165, "PG-13", 8.5, 2019)
```

















